### ISSUE TITLE
"ComputeImpl.cpp: 'Kore/WinError.h' file not found" fatal error on OSX

### ISSUE THREAD

**Issue by thoughton** [Kha-Samples/ComputeShader#2]
Hi,

I get the following error when trying to build on OSX 10.9.5:

```
/ComputeShader/Kha/Kore/Backends/OpenGL2/Sources/Kore/ComputeImpl.cpp:6:10: fatal error: 'Kore/WinError.h' file not found
#include <Kore/WinError.h>
         ^
1 warning and 1 error generated.
```

I was using the following command to build:

```
$ node Kha/make --run
```

Thanks!

**Comment by RobDangerous** [comment]
Hey, I already fixed that.
Won't help you on OSX though - it only got properly working compute support in 10.11 and only using Metal which I still have to get running on OSX. Previous OSX versions did support OpenCL but according to everything I read about it the implementation is so buggy that it's barely useful so I suppose it's not worth the work to add that.

**Comment by thoughton** [comment]
Ahhh thanks, I didn't realise all that. I'll save my compute experiments for my Windows box then. :)

**Comment by RobDangerous** [comment]
And make sure to add --graphics direct3d11 or --graphics opengl because on Windows Kha uses Direct3D9 by default which also doesn't support compute shaders.
